#!/usr/bin/env bash
# Install or upgrade the lodestar-harness enforcement layer (Readiness tier A)
# in a project.
#
# Usage: bootstrap.sh <project-dir> --stack <node-ts|python> [--upgrade]
#        bootstrap.sh <project-dir> --stack python=backend --stack node-ts=frontend
#
# A repo with several parts gets one Makefile per part, plus a root Makefile
# that runs each target in every part. Hooks and CI still call the root.
#
# [managed] files are created when missing; --upgrade overwrites them.
# [project] files are created when missing and never overwritten.
# An existing .claude/settings.json is merged: only missing hooks are added.
# Safe to run many times: a second run changes nothing.
set -euo pipefail

here=$(cd "$(dirname "$0")" && pwd)
lodestar=$(cd "$here/.." && { pwd -W 2>/dev/null || pwd; })
dir= upgrade=0 stacks=()
while [ $# -gt 0 ]; do
  case "$1" in
    --stack) read -ra s <<< "${2:-}"; stacks+=("${s[@]}"); shift ;;  # also the space-joined form .ai/enforcement.json records
    --upgrade) upgrade=1 ;;
    -h|--help) sed -n '2,14p' "$0"; exit 0 ;;
    *) dir=$1 ;;
  esac
  shift
done
[ -n "$dir" ] && [ ${#stacks[@]} -gt 0 ] ||
  { echo "Usage: bootstrap.sh <project-dir> --stack <$(ls "$here/stacks" | tr '\n' '|' | sed 's/|$//')>[=<subdir>] ... [--upgrade]" >&2; exit 1; }
parts=()
for s in "${stacks[@]}"; do
  [ -d "$here/stacks/${s%%=*}" ] || { echo "Unknown stack '${s%%=*}'. Choose one of: $(ls "$here/stacks" | tr '\n' ' ')" >&2; exit 1; }
  case "$s" in *=*) parts+=("${s#*=}") ;; esac
done
[ ${#parts[@]} = 0 ] || [ ${#parts[@]} = ${#stacks[@]} ] ||
  { echo "Give every --stack a subdir (stack=dir), or give a single --stack without one." >&2; exit 1; }
[ ${#parts[@]} -gt 0 ] || [ ${#stacks[@]} = 1 ] || { echo "Several stacks need subdirs: --stack <stack>=<dir>." >&2; exit 1; }
command -v jq >/dev/null || { echo "jq is required. See enforcement/README.md." >&2; exit 1; }
mkdir -p "$dir"
cd "$dir"

say() { printf '  %-8s %s\n' "$1" "$2"; }

# put SRC DST managed|project
put() {
  local src=$1 dst=$2 kind=$3
  if [ ! -e "$dst" ]; then
    mkdir -p "$(dirname "$dst")"; cp "$src" "$dst"; say created "$dst"
  elif [ "$kind" = managed ] && [ $upgrade = 1 ] && ! cmp -s "$src" "$dst"; then
    cp "$src" "$dst"; say updated "$dst"
  fi
}

# [managed]
for h in lodestar-lib lint-file verify-before-stop protect-tests sensitive-gate guard-install approval-record feedback-check ci-checks doctor; do
  put "$here/agents/claude/hooks/$h.sh" ".claude/hooks/$h.sh" managed
done
put "$here/github/ci.yml" .github/workflows/ci.yml managed
# Renamed in 2.0.0 (orca-lib.sh became lodestar-lib.sh).
if [ $upgrade = 1 ] && [ -f .claude/hooks/orca-lib.sh ]; then rm .claude/hooks/orca-lib.sh; say removed .claude/hooks/orca-lib.sh; fi

# [project]
put "$here/project/CLAUDE.md" CLAUDE.md project
put "$lodestar/project/.ai/project.md" .ai/project.md project
for f in invariants.md feedback-log.md tech-debt.md plans/TEMPLATE.md plans/active/.gitkeep plans/completed/.gitkeep; do
  put "$here/project/.ai/$f" ".ai/$f" project
done
for s in "${stacks[@]}"; do
  sub=.; case "$s" in *=*) sub=${s#*=} ;; esac
  for f in "$here/stacks/${s%%=*}"/* "$here/stacks/${s%%=*}"/.[!.]*; do
    [ -f "$f" ] && put "$f" "$sub/$(basename "$f")" project
  done
done

# Several parts: the root Makefile runs each target in every part that has
# it, and sends lint-file to the part that owns the file.
if [ ${#parts[@]} -gt 0 ]; then
  root=$(mktemp)
  {
    cat <<EOF
# Lodestar command contract (see lodestar-harness rules/enforcement.md).
# Repo with several parts: each target runs in every part that defines it.
# Generated by bootstrap.sh; this file belongs to the project.
PARTS := ${parts[*]}
TARGETS := setup lint format-check typecheck test verify verify-full
.PHONY: \$(TARGETS) lint-file test-mutation

\$(TARGETS):
EOF
    cat <<'EOF'
	@for p in $(PARTS); do \
	  if $(MAKE) -s -C $$p -n $@ >/dev/null 2>&1; then $(MAKE) --no-print-directory -C $$p $@ || exit 1; fi; \
	done

# Mutation testing: each part gets its own files, relative to the part.
test-mutation:
	@for p in $(PARTS); do \
	  f=$$(printf '%s\n' $(FILES) | sed -n "s#^$$p/##p"); \
	  if [ -n "$$f" ] && $(MAKE) -s -C $$p -n test-mutation >/dev/null 2>&1; then \
	    $(MAKE) --no-print-directory -C $$p test-mutation FILES="$$(echo $$f)" || exit 1; fi; \
	done

# Send the file to the part that owns it (slashes normalized for Windows).
lint-file:
	@case "$(subst \,/,$(FILE))" in \
EOF
    for p in "${parts[@]}"; do
      printf '\t  */%s/*) $(MAKE) --no-print-directory -C %s lint-file FILE="$(FILE)" ;; \\\n' "$p" "$p"
    done
    printf '\tesac\n'
  } > "$root"
  put "$root" Makefile project
  rm -f "$root"
fi

# Maintenance clock (workflows/maintenance.md) starts at onboarding.
if [ ! -f .ai/last-maintenance ]; then
  date +%F > .ai/last-maintenance; say created .ai/last-maintenance
fi

# .ai/handoff.md: where the last session stopped. Local only: agents may not
# push to main, so a committed handoff would need a PR after every task.
if ! grep -qxF '.ai/handoff.md' .gitignore 2>/dev/null; then
  [ -s .gitignore ] && [ -n "$(tail -c1 .gitignore)" ] && echo >> .gitignore   # no newline at end
  echo '.ai/handoff.md' >> .gitignore; say updated .gitignore
fi

# Line endings. With core.autocrlf=true (common on Windows) git checks files
# out as CRLF, and formatters such as Prettier then fail on every file.
# A new repo (no commits yet) gets LF for all text files; an existing repo
# only gets it for shell scripts, so its files are not renormalized at once.
if ! git rev-parse -q --verify HEAD >/dev/null 2>&1; then
  if ! grep -qxF '* text=auto eol=lf' .gitattributes 2>/dev/null; then
    echo '* text=auto eol=lf' >> .gitattributes; say updated .gitattributes
  fi
elif ! grep -qxF '*.sh text eol=lf' .gitattributes 2>/dev/null; then
  echo '*.sh text eol=lf' >> .gitattributes; say updated .gitattributes
fi

# .claude/settings.json: add our hooks, keep everything else.
# ponytail: matches hooks by exact command string; if a new template version
# changes a command, --upgrade adds it next to the old one. Remove the old
# entry by hand, or match by script name if that starts to happen.
ours="$here/agents/claude/settings.json"
if [ ! -f .claude/settings.json ]; then
  put "$ours" .claude/settings.json managed
else
  merged=$(jq -s '
    def cmds: [.[]?.hooks[]?.command];
    .[0] as $cur | .[1] as $ours
    | $cur | .hooks = reduce ($ours.hooks | to_entries[]) as $e (($cur.hooks // {});
        (.[$e.key] // []) as $arr | ($arr | cmds) as $have
        # Compare hook by hook: a group may gain a new hook in a later version.
        | .[$e.key] = $arr + [$e.value[]
            | .hooks |= map(select(.command as $c | ($have | index($c)) == null))
            | select(.hooks | length > 0)])
  ' .claude/settings.json "$ours" | tr -d '\r')
  if [ "$merged" != "$(jq . .claude/settings.json | tr -d '\r')" ]; then
    printf '%s\n' "$merged" > .claude/settings.json; say merged .claude/settings.json
  fi
fi

# .ai/enforcement.json: which template version this project runs, and where
# lodestar-harness lives: "source" on this machine, "repo" for agents that run
# elsewhere (cloud maintenance). Empty when lodestar-harness has no origin
# remote (a downloaded copy).
repo=$({ git -C "$lodestar" remote get-url origin 2>/dev/null || true; } | sed -E 's#^git@([^:]+):#https://\1/#; s#\.git$##')
want=$(jq -n --arg v "$(tr -d '\r\n' < "$here/VERSION")" --arg s "${stacks[*]}" --arg o "$lodestar" --arg r "$repo" \
  '{version: $v, stack: $s, source: $o, repo: $r}' | tr -d '\r')
if [ ! -f .ai/enforcement.json ] ||
   { [ $upgrade = 1 ] && [ "$want" != "$(tr -d '\r' < .ai/enforcement.json)" ]; }; then
  printf '%s\n' "$want" > .ai/enforcement.json; say wrote .ai/enforcement.json
fi

# Native Windows make cannot run in a folder whose path has accents.
if w=$(pwd -W 2>/dev/null) && LC_ALL=C grep -q '[^ -~]' <<<"$w"; then
  echo "WARNING: the project path has accented characters ($w)."
  echo "  make on Windows cannot run there, so hooks and 'make verify' will fail. Rename the folder."
fi

# Enforcement files that git ignores never reach the repo, so hooks and CI
# silently vanish for everyone else.
if git rev-parse --git-dir >/dev/null 2>&1; then
  ignored=$(git check-ignore .claude/settings.json .claude/hooks/*.sh .github/workflows/ci.yml .ai/*.md .ai/enforcement.json 2>/dev/null | grep -vxF .ai/handoff.md || true)
  if [ -n "$ignored" ]; then
    echo "WARNING: .gitignore hides these enforcement files. Unignore them (e.g. !.claude/settings.json, !.claude/hooks/):"
    printf '  %s\n' $ignored
  fi
fi

echo "Done. Next: fill in CLAUDE.md and .ai/project.md, then run: bash .claude/hooks/doctor.sh"
